// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPOdpdeXQ-nRTf-FtGM-NU7X77fobGhg',
    appId: '1:863348880724:web:9d6d67e566359e9c2784c1',
    messagingSenderId: '863348880724',
    projectId: 'soft-skill-app-39a74',
    authDomain: 'soft-skill-app-39a74.firebaseapp.com',
    storageBucket: 'soft-skill-app-39a74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG07-CkW655KoTbSeEECSuX7Q888fNKv0',
    appId: '1:863348880724:android:52a3cbcff0b309382784c1',
    messagingSenderId: '863348880724',
    projectId: 'soft-skill-app-39a74',
    storageBucket: 'soft-skill-app-39a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndHht7KhYOb0iuQWS3W9lHlpchF99N3g',
    appId: '1:863348880724:ios:3f9dcc51d6fb6ee32784c1',
    messagingSenderId: '863348880724',
    projectId: 'soft-skill-app-39a74',
    storageBucket: 'soft-skill-app-39a74.appspot.com',
    androidClientId: '863348880724-v0a9uc2lbkr5p9tkvr5i90apve0iovrj.apps.googleusercontent.com',
    iosClientId: '863348880724-pi2ibb8beb4a9aqgijbcvoocc6vbjmlm.apps.googleusercontent.com',
    iosBundleId: 'com.hex.hackathon.softApp',
  );
}
